-- 여로 서비스의 초기 데이터베이스 스키마
-- 이 파일은 적용된 이후 수정하지 않고, 변경 사항은 새로운 버전의 마이그레이션으로 추가한다.

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL UNIQUE,
    nickname            VARCHAR(30)  NOT NULL UNIQUE,
    profile_image_url   VARCHAR(500),
    role                VARCHAR(20)  NOT NULL DEFAULT 'USER',
    account_status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    restriction_ends_at TIMESTAMPTZ,
    terms_agreed_at     TIMESTAMPTZ  NOT NULL,
    privacy_agreed_at   TIMESTAMPTZ  NOT NULL,
    last_login_at       TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_role
        CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT chk_users_account_status
        CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE TABLE social_accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    provider         VARCHAR(20)  NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_social_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_social_accounts_provider_user
        UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_social_accounts_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT chk_social_accounts_provider
        CHECK (provider IN ('GOOGLE', 'KAKAO'))
);
