spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/yeoro
    username: yeoro
    password: yeoro-local-password
  docker:
    compose:
      file: docker-compose-local.yaml
